# Generated by Django 3.2.6 on 2021-08-07 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='is_seen',
            new_name='is_read',
        ),
    ]
