# Generated by Django 3.2.6 on 2021-08-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_rename_is_seen_notification_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'Message'), ('application', 'Application')], max_length=20),
        ),
    ]
